spring.application.name=ms-payments
server.port=8083

# MongoDB Config
spring.data.mongodb.uri=${MONGODB_URI:mongodb+srv://BrunoDB:fBwqgjn4Up5fF5SG@cluster0.r6if00t.mongodb.net/paymentsdb?retryWrites=true&w=majority&appName=Cluster0}

# RabbitMQ Config
spring.rabbitmq.addresses=${RABBITMQ_URI:amqps://wfkwwege:MXhjPUXvCp_hdMeVg_16cIXLW0Hta4rc@gull.rmq.cloudamqp.com/wfkwwege}